// Schema or Data
import type { StockHolding } from './types';

export const portfolioData: StockHolding[] = [
  {
    stockName: 'TCS',
    exchange: 'NSE',
    symbol: 'TCS.NS',
    purchasePrice: 3500,
    quantity: 10,
    sector: 'Technology',
  },
  {
    stockName: 'INFY',
    exchange: 'NSE',
    symbol: 'INFY.NS',
    purchasePrice: 1400,
    quantity: 20,
    sector: 'Technology',
  },
  {
    stockName: 'HDFC Bank',
    exchange: 'NSE',
    symbol: 'HDFCBANK.NS',
    purchasePrice: 1500,
    quantity: 15,
    sector: 'Financials',
  },
  {
    stockName: 'Reliance Industries',
    exchange: 'NSE',
    symbol: 'RELIANCE.NS',
    purchasePrice: 2400,
    quantity: 12,
    sector: 'Energy',
  },
  {
    stockName: 'ICICI Bank',
    exchange: 'NSE',
    symbol: 'ICICIBANK.NS',
    purchasePrice: 700,
    quantity: 25,
    sector: 'Financials',
  },
  {
    stockName: 'Larsen & Toubro',
    exchange: 'NSE',
    symbol: 'LT.NS',
    purchasePrice: 2100,
    quantity: 8,
    sector: 'Infrastructure',
  },
  {
    stockName: 'Maruti Suzuki',
    exchange: 'NSE',
    symbol: 'MARUTI.NS',
    purchasePrice: 8000,
    quantity: 5,
    sector: 'Automobile',
  },
  {
    stockName: 'Bharti Airtel',
    exchange: 'NSE',
    symbol: 'BHARTIARTL.NS',
    purchasePrice: 600,
    quantity: 30,
    sector: 'Telecom',
  },
  {
    stockName: 'Kotak Mahindra Bank',
    exchange: 'NSE',
    symbol: 'KOTAKBANK.NS',
    purchasePrice: 1900,
    quantity: 10,
    sector: 'Financials',
  },
  {
    stockName: 'Axis Bank',
    exchange: 'NSE',
    symbol: 'AXISBANK.NS',
    purchasePrice: 850,
    quantity: 18,
    sector: 'Financials',
  },
  {
    stockName: 'Asian Paints',
    exchange: 'NSE',
    symbol: 'ASIANPAINT.NS',
    purchasePrice: 3200,
    quantity: 7,
    sector: 'Consumer Goods',
  },
  {
    stockName: 'Titan Company',
    exchange: 'NSE',
    symbol: 'TITAN.NS',
    purchasePrice: 2500,
    quantity: 9,
    sector: 'Consumer Goods',
  },
  {
    stockName: 'SBI Life Insurance',
    exchange: 'NSE',
    symbol: 'SBILIFE.NS',
    purchasePrice: 1100,
    quantity: 14,
    sector: 'Financials',
  },
  {
    stockName: 'Bajaj Housing Finance',
    exchange: 'NSE',
    symbol: 'BAJAJHLDNG.NS',
    purchasePrice: 600,
    quantity: 20,
    sector: 'Financials',
  },
  {
    stockName: 'IDFC Bank',
    exchange: 'NSE',
    symbol: 'IDFCFIRSTB.NS',
    purchasePrice: 55,
    quantity: 100,
    sector: 'Financials',
  },
  {
    stockName: 'KPIT Technologies',
    exchange: 'NSE',
    symbol: 'KPITTECH.NS',
    purchasePrice: 320,
    quantity: 25,
    sector: 'Technology',
  },
  {
    stockName: 'LTI Mindtree',
    exchange: 'NSE',
    symbol: 'LTI.NS',
    purchasePrice: 3200,
    quantity: 10,
    sector: 'Technology',
  },
  {
    stockName: 'Dmart',
    exchange: 'NSE',
    symbol: 'DMART.NS',
    purchasePrice: 2800,
    quantity: 8,
    sector: 'Retail',
  },
  {
    stockName: 'Tata Consumer Products',
    exchange: 'NSE',
    symbol: 'TATACONSUM.NS',
    purchasePrice: 700,
    quantity: 15,
    sector: 'Consumer Goods',
  },
];
